### ISSUE TITLE
[Bug]: Updating to Ars 3.4.5 stops the game form working

### ISSUE THREAD

**Issue by Tradonix** [Mrbysco/GeoreNouveau#1]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.1.47

### Mod version

0.2.0

### Java version

curse forge auto

### Issue Description

Ars Nouveau ver 3.4.5
After starting the game, launcher disappears like normal, the game window flickers on for a sec and then disappears, process gets stuck.
Seams like 3.4.5 broke something (works normally on 3.4.3.).

**Comment by Mrbysco** [comment]
A new version will be out shortly
